# Generated by Django 5.2 on 2025-04-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Без категории', max_length=255),
        ),
    ]
